# Generated by Django 5.1.3 on 2024-11-17 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osdf', '0003_post_downvoted_by_post_upvoted_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reported_by',
            field=models.ManyToManyField(blank=True, related_name='reported_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
